basic.forever(function () {
    basic.showString("KAIXO")
    basic.pause(200)
    basic.showString("I")
    basic.pause(200)
    basic.showString("A")
    basic.pause(200)
    basic.showString("M")
    basic.pause(200)
    basic.showString("NAIZ")
    basic.pause(200)
})
